version: '1'
services:
  db:
    image: mongo
    volumes:
      - dbdata:/data/db
  backend:
    build: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://db:27017
      - DB_NAME=todo-app
      - CLOUDINARY_CLOUD_NAME=<your cloud name>
      - CLOUDINARY_API_KEY=<your api key>
      - CLOUDINARY_API_secret=<your api secret>
      - JWT_SECRET=secret
      - JWT_EXPITY=7d
      - NODE_ENV=development
  frontend:
    build: frontend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000/api/v1
    ports:
      - "3000:3000"
volumes:
  dbdata: